### ISSUE TITLE
Stop publicizing other organization intellectual property

### ISSUE THREAD

**Issue by sourabh0108** [Akash-Mittal/consuming-nasa-apis#4]
Kindly remove this code from Github as this breaches the intellectual property contract.
You are not suppose to make this code public and make other candidates rejected in their interviews.

NOTE: Any candidate found copying or referring this code will be rejected immediately.

**Comment by Akash-Mittal** [comment]
Thanks for your suggestion - the Challenge may be from any company - however the solution is made from scratch by the contributer.

However - the docs should have a disclaimer for education purpose also - Updating it right now.
